version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production